name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Test ${{ matrix.os }}
    runs-on: 'windows-latest'
    steps:
      - name: Configure Windows environment variables
        if: matrix.os == 'windows-latest'
        run: |
          # echo "::set-env name=SHELLFLAGS::-x"
          echo "::set-env name=BUILDFLAGS::"
          echo "::set-env name=RSPY_TARGET_DIR::$env:GITHUB_WORKSPACE\target"
          echo "::set-env name=CARGO_TARGET_DIR::$env:GITHUB_WORKSPACE\target"

          # https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio
          if( "3.7".equals( "${{ matrix.python }}" ) ) {
            $pyaudio=("PyAudio-0.2.11-cp37-cp37m-win_amd64.whl")
          }
          else {
            $pyaudio=("PyAudio-0.2.11-cp38-cp38-win_amd64.whl")
          }

          $new_path=("$env:GITHUB_WORKSPACE;$env:PATH")
          $new_path=("$env:GITHUB_WORKSPACE\shims;$new_path")

          echo "::set-env name=pacmanbin::pacman-5.1.1-3-x86_64.pkg.tar.xz"
          echo "::set-env name=pacmanmirror::pacman-mirrors-20200307-1-any.pkg.tar.xz"
          echo "::set-env name=pacmankeys::msys2-keyring-r9.397a52e-1-any.pkg.tar.xz"
          echo "::set-env name=pyaudio::$pyaudio"
          echo "::set-env name=PATH::$new_path"
          echo "::set-env name=RUST_BACKTRACE::full"
          echo "::set-env name=SCOOP::$env:GITHUB_WORKSPACE"
          echo "::set-env name=SCOOP_GLOBAL::$env:GITHUB_WORKSPACE"
          echo "::set-env name=ANKI_EXTRA_PIP::python -m pip install $pyaudio"

      - name: Run commands
        shell: cmd
        run: |
          echo on
          curl -LO http://repo.msys2.org/msys/x86_64/%pacmanbin%
          curl -LO http://repo.msys2.org/msys/x86_64/%pacmanmirror%
          curl -LO http://repo.msys2.org/msys/x86_64/%pacmankeys%

          :: https://stackoverflow.com/questions/1359793/programmatically-extract-tar-gz
          7z x "%pacmanbin%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"
          7z x "%pacmanmirror%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"
          7z x "%pacmankeys%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"

          :: Manually Install Pacman Binaries
          :: https://github.com/Alexpux/MSYS2-pacman/issues/50
          set "PATH=%programfiles%\Git\usr\bin"
          bash pacman-key --init
          bash pacman-key --populate msys2
          bash pacman-key --refresh-keys
          pacman -Tv
          pacman -Syyuuv --overwrite='*'
          pacman -Syuuv --overwrite='*'
          pacman --version

          :: We must install bash first, otherwise we will have bash fork errors:
          :: https://github.com/evandroforks/anki/runs/524857054?check_suite_focus=true
          :: 0 [main] pacman 748 dofork: child -1 - forked process 2896 died unexpectedly
          pacman -Sv --noconfirm --overwrite='*' bash
          pacman -Sv --noconfirm --overwrite='*' rsync

          :: clean all packages to decrease image size
          pacman -Sccv --noconfirm
          pacman -Qsv --noconfirm
