name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Test ${{ matrix.os }}
    runs-on: 'macos-latest'
    steps:
      - name: Run commands
        run: |
          set -x
          python --version
          python3 --version
          brew install python3
          python --version
          python3 --version
