name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Test ${{ matrix.os }}
    runs-on: 'windows-latest'
    steps:
      - name: Run commands
        run: |
          dir C:\msys64\usr\bin
          C:\msys64\usr\bin\pacman --version
