name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Test ${{ matrix.os }}
    runs-on: 'windows-latest'
    steps:
      - name: Configure Windows environment variables
        run: |
          # echo "::set-env name=SHELLFLAGS::-x"
          echo "::set-env name=BUILDFLAGS::"
          echo "::set-env name=RSPY_TARGET_DIR::$env:GITHUB_WORKSPACE\target"
          echo "::set-env name=CARGO_TARGET_DIR::$env:GITHUB_WORKSPACE\target"

          # https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio
          if( "3.7".equals( "${{ matrix.python }}" ) ) {
            $pyaudio=("PyAudio-0.2.11-cp37-cp37m-win_amd64.whl")
          }
          else {
            $pyaudio=("PyAudio-0.2.11-cp38-cp38-win_amd64.whl")
          }

          $new_path=("$env:GITHUB_WORKSPACE;$env:PATH")
          $new_path=("$env:GITHUB_WORKSPACE\shims;$new_path")

          echo "::set-env name=rsyncbin::rsync-3.1.3-1-x86_64.pkg.tar.xz"
          echo "::set-env name=pyaudio::$pyaudio"
          echo "::set-env name=PATH::$new_path"
          echo "::set-env name=RUST_BACKTRACE::full"
          echo "::set-env name=SCOOP::$env:GITHUB_WORKSPACE"
          echo "::set-env name=SCOOP_GLOBAL::$env:GITHUB_WORKSPACE"
          echo "::set-env name=ANKI_EXTRA_PIP::python -m pip install $pyaudio"

      - name: Run commands
        shell: cmd
        run: |
          echo on
          curl -LO http://repo.msys2.org/msys/x86_64/%rsyncbin%

          :: https://stackoverflow.com/questions/1359793/programmatically-extract-tar-gz
          7z x "%rsyncbin%" -so | 7z x -aoa -si -ttar -o"%programfiles%\Git"

          rsync --version
