name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install things
      run: |
        set -x
        echo "::set-env name=PATH::/usr/local/opt/make/libexec/gnubin:$PATH"
        brew install tree
        make --version
        brew install make
        make --version
        gmake --version
        which -a make
        which -a gmake

    - name: Configure environment variables
      run: |
        echo Nothing.

    - name: Check things
      run: |
        set -x
        make --version
        gmake --version
        tree /usr/local/opt/

    - name: Explicitly export PATH
      run: |
        set -x
        export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
        make --version
        gmake --version
        tree /usr/local/opt/
