name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure environment variables
      run: |
        echo "::set-env name=PATH::/usr/local/opt/make/libexec/gnubin:$PATH"

    - name: Run commands
      run: |
        set -x
        make --version
        brew install make
        make --version
