name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure environment variables
      run: |
        set -x
        make --version
        rsync --version
        brew install rsync make
        make --version
        rsync --version
