name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      - name: Configure environment variables
        run: |
          make --version
          brew install rsync
          make --version
          brew install make
